#######################################
# 抖音下载器配置文件
# 简洁版配置 - 只保留必要选项
#######################################

# 下载链接（支持多个）
link:
  # 测试用户主页下载
  - https://www.douyin.com/user/MS4wLjABAAAAKObjGd_jd_XEApix_0X_KpLxehvQTm-IBxIAcYE8DMmFbPTKDj6tqGNzglTBYI8F?from_tab_name=main&vid=7515590836927614242
  # 或者使用短链接（实际上也是用户主页）
  # - https://v.douyin.com/iRGu2mBL/

# 保存路径
path: ./Downloaded/

# 下载选项
music: true      # 下载音乐
cover: true      # 下载封面
avatar: false    # 下载头像
json: true       # 保存元数据

# 时间过滤（可选，格式：YYYY-MM-DD）
start_time: ""   # 开始时间
end_time: ""     # 结束时间

# 用户主页下载模式
mode:
  - post         # 发布的作品
  # - like       # 喜欢的作品

# 下载数量限制（0=全部）
number:
  post: 2        # 用户作品数量（测试只下载2个）
  like: 0        # 喜欢作品数量

# 性能设置
thread: 5        # 并发线程数
retry_times: 3   # 重试次数

# Cookie配置（必需）
cookies:
  msToken: 710-fIIacqPfoNUNM8EKjH2ev0veFV2YZCtCfs_HoN7kjpBKubLAODdh0nStKywolHK2nsJFHmdimUN23q-lo41pxjuiNMoqG1p_yUoIKU0CJ9bX-Q0638LXozcxspQnrzDnHB4M_3Hu3GljVuPYvv-8nHrxp4Xqkw-Bcr0MeothxDuPtHlEBA==
  ttwid: 1%7Cz6JSDcLnxCI34WFpVEtasnL34J0NIzuVUBLiBMJ3Lf8%7C1758457782%7C8ead48675cc3b74fdd97da86172f5d97e5b8b0ea22a14839cbac57b2ce517311
  odin_tt: c900d73b099420aa11e3d4d1d63e2a710ee31db6e4d444b805cd28c3405f2b5d6d66031a9337351c3c0654ceb3a9c5b6fbe3057eb9de15cf87e3992942d0627b
  passport_csrf_token: 69f583248417443c3bf747b4dd3b8ca8
  sid_guard: 6e05153b37bf5cc8951e768bac7e86ef%7C1757897479%7C5184000%7CFri%2C+14-Nov-2025+00%3A51%3A19+GMT


# passport_csrf_token=69f583248417443c3bf747b4dd3b8ca8;
# ttwid=1%7Cz6JSDcLnxCI34WFpVEtasnL34J0NIzuVUBLiBMJ3Lf8%7C1758457782%7C8ead48675cc3b74fdd97da86172f5d97e5b8b0ea22a14839cbac57b2ce517311;
# sessionid=6e05153b37bf5cc8951e768bac7e86ef; 
# sessionid_ss=6e05153b37bf5cc8951e768bac7e86ef;
# sid_guard=6e05153b37bf5cc8951e768bac7e86ef%7C1757897479%7C5184000%7CFri%2C+14-Nov-2025+00%3A51%3A19+GMT; 